In [1]:
import torch

In [2]:
input = torch.ones(1, 1, 5, 5)
print(input)

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])


In [9]:
x = torch.nn.Conv2d(1, 3, 3, 1)
print(list(x.parameters()))

[Parameter containing:
tensor([[[[ 0.2609, -0.0988, -0.2838],
          [-0.2735,  0.3293,  0.1592],
          [-0.2607,  0.2460, -0.3254]]],


        [[[-0.1072,  0.1700,  0.2453],
          [-0.1815, -0.1612,  0.1041],
          [ 0.2713,  0.1281, -0.0292]]],


        [[[-0.1953, -0.0965,  0.0642],
          [-0.2086, -0.0451,  0.1522],
          [ 0.1305,  0.1031,  0.2010]]]], requires_grad=True), Parameter containing:
tensor([0.3232, 0.1169, 0.1350], requires_grad=True)]


In [12]:
out = x(input)
print(out)

tensor([[[[0.0763, 0.0763, 0.0763],
          [0.0763, 0.0763, 0.0763],
          [0.0763, 0.0763, 0.0763]],

         [[0.5566, 0.5566, 0.5566],
          [0.5566, 0.5566, 0.5566],
          [0.5566, 0.5566, 0.5566]],

         [[0.2404, 0.2404, 0.2404],
          [0.2404, 0.2404, 0.2404],
          [0.2404, 0.2404, 0.2404]]]], grad_fn=<ThnnConv2DBackward>)
