In [1]:
import torch

In [2]:
import numpy as np

In [3]:
np_data = np.arange(6).reshape(2, 3)

In [4]:
torch_data = torch.from_numpy(np_data)

In [5]:
print(np_data)
print(torch_data)

[[0 1 2]
 [3 4 5]]
tensor([[0, 1, 2],
        [3, 4, 5]])


In [6]:
torch2np = torch_data.numpy()

In [7]:
print(torch2np)

[[0 1 2]
 [3 4 5]]


In [11]:
# operations
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data) # 32 bits
print(tensor)

tensor([-1., -2.,  1.,  2.])


In [9]:
print(torch.abs(tensor))

tensor([1., 2., 1., 2.])


In [10]:
print(torch.sin(tensor))

tensor([-0.8415, -0.9093,  0.8415,  0.9093])


In [12]:
# matrix operations

In [13]:
data1 = [[1, 2], [3, 4]]
tensor1 = torch.FloatTensor(data1)
print(tensor1)

tensor([[1., 2.],
        [3., 4.]])


In [14]:
print(torch.matmul(tensor1, tensor1))

tensor([[ 7., 10.],
        [15., 22.]])
