In [1]:
import torch
from torch.autograd import Variable

In [8]:
tensor = torch.FloatTensor([[1, 2], [3, 4]])
variable = Variable(tensor, requires_grad=True)
print(variable)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [4]:
v_out = torch.mean(variable * variable)
print(v_out)

tensor(7.5000, grad_fn=<MeanBackward1>)


In [5]:
v_out.backward()
print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [7]:
print(variable.data)

tensor([[1., 2.],
        [3., 4.]])

In [9]:
print(variable.data.numpy())

[[1. 2.]
 [3. 4.]]
